### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by Dontmindmes** [sithis993/Crypter#29]
https://gyazo.com/dec38bb90e8c1828d2474255d8c680b0
C:\Users\***\Desktop\Python\build>python Builder.py
python: can't open file 'Builder.py': [Errno 2] No such file or directory

CMD is ran as admin

**Comment by Dontmindmes** [comment]
Also when i want to isntall ordereddict i get this \Desktop\Python\ordereddict-1.1>python setup.py
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

using windows 10

**Comment by Dontmindmes** [comment]
I also get this error line 13, in <module>
C:\Users\**\Desktop\Python\build>python Builder.pyw
Traceback (most recent call last):
  File "Builder.pyw", line 8, in <module>
    import ExeBuilder
  File "C:\Users\**\Desktop\Python\build\ExeBuilder\__init__.py", line 13, in <module>
    from .ExeBuilder import ExeBuilder
  File "C:\Users\**\Desktop\Python\build\ExeBuilder\ExeBuilder.py", line 7, in <module>
    import wx
ModuleNotFoundError: No module named 'wx'

**Comment by Dontmindmes** [comment]
I also get this error when im installing the .tgz

Exception:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\python27\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "c:\python27\lib\site-packages\pip\download.py", line 809, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "c:\python27\lib\site-packages\pip\download.py", line 715, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "c:\python27\lib\site-packages\pip\utils\__init__.py", line 602, in unpack_file
    tarfile.is_tarfile(filename) or
  File "c:\python27\lib\tarfile.py", line 2624, in is_tarfile
    t = open(name)
  File "c:\python27\lib\tarfile.py", line 1675, in open
    return func(name, "r", fileobj, **kwargs)
  File "c:\python27\lib\tarfile.py", line 1740, in gzopen
    fileobj = gzip.GzipFile(name, mode, compresslevel, fileobj)
  File "c:\python27\lib\gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: 'C:\\Users\\****\\Desktop\\dependencies\\ordereddict-1.1.tar'

**Comment by Dontmindmes** [comment]
I also get this

pip install PyInstaller-3.1.1.tar
Requirement 'PyInstaller-3.1.1.tar' looks like a filename, but the file does not exist

**Comment by Dontmindmes** [comment]
NVM i have solved everything
